#!/bin/bash
DWM=$(
  cd $(dirname "$0")
  pwd
)

# core components
remapkey &
$(remapkey && ibus-daemon -rdx) &
#brightness set 0.8 &
$DWM/dwmbar &
# /usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd &

# locker
# xss-lock i3lock &
xset dpms 0 0 300 &                              # turn off screen after 3m
# xautolock -time 20 -locker "systemctl suspend" & # suspend after 5m

# keyboard rate: 150 delay + 40hz
xset r rate 150 40 &

RANDOM_WALLPAPER=$(find "$DWM/wallpaper-dark" | shuf -n 1)
feh --bg-scale "$RANDOM_WALLPAPER" &

xrdb ~/.config/Xresources.d/main.Xresources & # theming

firefox &

# unimportant tasks
sleep 3s

copyq &
dunst &
picom --backend=glx &
ghostty --initial-command="tmux new -A -s floaty" --x11-instance-name="floatyghostty" &
dolphin &
uv run "$DWM/play-sound-on-connect.py" & 

function notfy_sleep_time {
  while true; do
    if [ "$(date +%H)" -ge 23 ]; then
      while true; do
          notify-send "Good night" "It's time to sleep"
          sound &
          sleep 1
      done;
    fi
    sleep 20
  done;
}

notfy_sleep_time &

