#!/bin/bash
function mydate {
	echo "$(date "+%a %d/%m %T")"
}

function battery {
	battery0=$(cat /sys/class/power_supply/BAT0/capacity)
	battery1=$(cat /sys/class/power_supply/BAT1/capacity)
	if [[ "$(cat /sys/class/power_supply/AC/online)" == "1" ]]; then
		echo -n C
	fi
	echo $(((battery0 + battery1) / 2))
}

function battery_lenovo {
	battery0=$(cat /sys/class/power_supply/BAT0/capacity)
	if [[ "$(cat /sys/class/power_supply/ADP0/online)" == "1" ]]; then
		echo -n C
	fi
	echo $battery0
}

function volume {
	volume=$(pamixer --get-volume)
	muted=$(pamixer --get-mute)
	if [ "$muted" = "true" ]; then
		echo "muted"
		return 0
	fi
	if [ "$volume" -le 33 ]; then
		echo "$volume"
	elif [ "$volume" -le 66 ]; then
		echo "$volume"
	else
		echo "$volume"
	fi
}

function ram_usage {
	free -m | grep '^Mem' | awk '{print $3"MB"}'
}

function cpu_temp {
	echo $(sensors -u | rg temp1_input | awk -c 'NR==1{sub(/\..*/,""); print$2}')C
}

function cpu_usage {
 awk '{print $1}' < /proc/loadavg
}

function update_dwmbar {
	bar="| \
"$(cpu_usage &)" \
"$(ram_usage &)" | \
"$(volume &)" | \
"$(mydate)" | \
"$(battery_lenovo &)" |"
	xsetroot -name "$bar"
}

while true; do
	if ! find /tmp/dwmbar-queue*; then
		update_dwmbar
	fi
  sleep 5
done
