#!/bin/bash
function mydate {
	echo "$(date "+%a %d/%m %T")"
}

## could still be useful for other laptops with multiple cells
# function battery {
# 	battery0=$(cat /sys/class/power_supply/BAT0/capacity)
# 	battery1=$(cat /sys/class/power_supply/BAT1/capacity)
# 	if [[ "$(cat /sys/class/power_supply/AC/online)" == "1" ]]; then
# 		echo -n C
# 	fi
# 	current_battery=$(((battery0 + battery1) / 2))
#   if [[ current_battery -lt 10 ]]; then
#     notify-send -u critical "Low battery" "Battery is at $current_battery%. Please plug in the charger."
#   fi
#   echo "$current_battery"
# }

## TODO: convert to accept arguments: battery paths
function battery_lenovo {
	battery0=$(cat /sys/class/power_supply/BAT0/capacity)
	if [[ "$(cat /sys/class/power_supply/ADP0/online)" == "1" ]]; then
		echo -n C
        elif [[ battery0 -lt 10 ]]; then
		notify-send -u critical "Low battery" "Battery is at $battery0%. Please plug in the charger."
        fi
	echo $battery0
}

function volume {
	volume=$(pamixer --get-volume)
	muted=$(pamixer --get-mute)
	if [ "$muted" = "true" ]; then
		echo "muted"
		return 0
	fi
	if [ "$volume" -le 33 ]; then
		echo "$volume"
	elif [ "$volume" -le 66 ]; then
		echo "$volume"
	else
		echo "$volume"
	fi
}

function ram_usage {
	free -m | grep '^Mem' | awk '{print $3"MB"}'
}

function cpu_temp {
	echo $(sensors -u | rg temp1_input | awk -c 'NR==1{sub(/\..*/,""); print$2}')C
}

function cpu_usage {
 top -bn2 | grep '%Cpu' | tail -1 | grep -P '(....|...) id,'|awk '{print 100-$8 "%"}'
}

function update_dwmbar {
	bar="| \
"$(cpu_usage &)" \
"$(ram_usage &)" | \
"$(volume &)" | \
"$(mydate)" | \
"$(battery_lenovo &)" |"
	xsetroot -name "$bar"
}

while true; do
	if ! find /tmp/dwmbar-queue*; then
		update_dwmbar &
	fi
  sleep 5
done
